{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "treepage-backend.fullname" . }}-api
  labels:
    {{- include "treepage-backend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host | quote }}
      secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" (include "treepage-backend.fullname" .)) }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          {{- if .Values.auth.enabled }}
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "treepage-backend.fullname" . }}-auth
                port:
                  number: {{ .Values.auth.service.port }}
          {{- end }}
          {{- if .Values.server.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "treepage-backend.fullname" . }}-server
                port:
                  number: {{ .Values.server.service.port }}
          {{- end }}
{{- end }}
